;==============================================================================
; PMI runtime library - String operations
;------------------------------------------------------------------------------
; API
;==============================================================================

%include "rtl/consts/string.inc"

extern str_len
extern str_reverse
extern str_copy
extern str_append
extern str_char_pos
extern str_char_rpos
extern str_cmp
extern str_int
extern str_fixed
extern str_hex
extern str_format
extern str_parse_int
extern str_parse_fixed
extern str_parse_hex
