;==============================================================================
; PMI runtime library - System timer
;------------------------------------------------------------------------------
; API
;==============================================================================

extern systimer_start
extern systimer_stop
extern systimer_set_timeout
extern systimer_clear_timeout
extern systimer_ticks
