;==============================================================================
; PMI runtime library - Timer (IRQ 0) handling
;------------------------------------------------------------------------------
; API
;==============================================================================

extern timer_calc_rate
extern timer_set_rate
extern timer_reset_rate
extern timer_start
extern timer_stop
