;==============================================================================
; Protected mode interface - Memory management
;------------------------------------------------------------------------------
; API
;==============================================================================

extern mem_alloc
extern mem_free
extern mem_setup
extern mem_alloc_addr
extern mem_split_block
extern mem_merge_blocks
