;==============================================================================
; PMI runtime library - String operations
;------------------------------------------------------------------------------
; Constants
;==============================================================================

;------------------------------------------------------------------------------
; Conversion type constants
;------------------------------------------------------------------------------

STR_CV_UNSIGNED	EQU 0			; Unsigned value conversion
STR_CV_SIGNED	EQU 1			; Signed value conversion
STR_CV_LOWER	EQU 0			; Lowercase conversion
STR_CV_UPPER	EQU 1			; Uppercase conversion
